import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:go_router/go_router.dart';

import '../../l10n/app_localizations.dart';
import '../../core/models/transaction_model.dart';
import '../../core/theme/app_colors.dart';
import '../../core/theme/app_radius.dart';
import '../../core/widgets/custom_text_field.dart';
import '../../core/localization/translation_helper.dart';
import '../../core/utils/icon_helper.dart';
import '../../services/auth_service.dart';
import '../../services/firestore_service.dart';

class NewTransactionScreen extends ConsumerStatefulWidget {
  const NewTransactionScreen({super.key});

  @override
  ConsumerState<NewTransactionScreen> createState() =>
      _NewTransactionScreenState();
}

class _NewTransactionScreenState extends ConsumerState<NewTransactionScreen> {
  String _type = 'expense'; // expense or income
  final _amountController = TextEditingController();
  final _titleController = TextEditingController();
  String? _selectedCategoryId;
  String? _selectedCategoryName;
  String? _selectedCategoryIcon;
  bool _isLoading = false;

  @override
  void initState() {
    super.initState();
    _amountController.text = '0.00';
  }

  @override
  void dispose() {
    _amountController.dispose();
    _titleController.dispose();
    super.dispose();
  }

  Future<void> _handleSave() async {
    final l10n = AppLocalizations.of(context);

    // Validate fields
    if (_titleController.text.isEmpty) {
      ScaffoldMessenger.of(
        context,
      ).showSnackBar(SnackBar(content: Text(l10n.pleaseEnterTitle)));
      return;
    }

    final amount = double.tryParse(_amountController.text) ?? 0.0;
    if (amount <= 0) {
      ScaffoldMessenger.of(
        context,
      ).showSnackBar(SnackBar(content: Text(l10n.pleaseEnterAmount)));
      return;
    }

    if (_selectedCategoryId == null) {
      ScaffoldMessenger.of(
        context,
      ).showSnackBar(SnackBar(content: Text(l10n.pleaseSelectCategory)));
      return;
    }

    setState(() => _isLoading = true);
    try {
      final user = ref.read(authServiceProvider).currentUser;
      if (user == null) return;

      final transaction = TransactionModel(
        id: '', // Generated by firestore
        userId: user.uid,
        title: _titleController.text,
        amount: amount,
        type: _type,
        categoryId: _selectedCategoryId!,
        categoryName: _selectedCategoryName!,
        categoryIcon: _selectedCategoryIcon!,
        createdAt: DateTime.now(),
      );

      await ref.read(firestoreServiceProvider).addTransaction(transaction);
      if (mounted) {
        context.pop();
        ScaffoldMessenger.of(
          context,
        ).showSnackBar(SnackBar(content: Text(l10n.transactionAdded)));
      }
    } catch (e) {
      if (mounted) {
        ScaffoldMessenger.of(
          context,
        ).showSnackBar(SnackBar(content: Text('${l10n.error}: $e')));
      }
    } finally {
      if (mounted) setState(() => _isLoading = false);
    }
  }

  @override
  Widget build(BuildContext context) {
    final categoriesAsync = ref.watch(categoriesProvider);
    final l10n = AppLocalizations.of(context);
    final theme = Theme.of(context);

    return Scaffold(
      appBar: AppBar(
        title: Text(l10n.newTransaction, style: theme.textTheme.headlineSmall),
        centerTitle: true,
        backgroundColor: AppColors.background,
        elevation: 0,
        leading: IconButton(
          icon: const Icon(Icons.arrow_back, color: AppColors.textPrimary),
          onPressed: () => context.pop(),
        ),
        actions: [
          TextButton(
            onPressed: _isLoading ? null : _handleSave,
            child: Text(
              l10n.save,
              style: theme.textTheme.titleMedium?.copyWith(
                color: AppColors.primary,
                fontWeight: FontWeight.bold,
              ),
            ),
          ),
        ],
      ),
      body: SingleChildScrollView(
        padding: const EdgeInsetsDirectional.all(24),
        child: Column(
          children: [
            // Type Toggle
            _buildTypeToggle(l10n),
            const SizedBox(height: 32),

            // Amount Input
            _buildAmountInput(theme),
            const Divider(),
            const SizedBox(height: 24),

            // Title Input
            CustomTextField(
              hintText: l10n.enterTitle,
              controller: _titleController,
              prefixIcon: const Icon(Icons.edit, color: Colors.grey),
            ),
            const SizedBox(height: 32),

            // Categories Section
            Align(
              alignment: AlignmentDirectional.centerStart,
              child: Text(l10n.category, style: theme.textTheme.headlineSmall),
            ),
            const SizedBox(height: 16),

            // Categories Grid
            categoriesAsync.when(
              data: (categories) =>
                  _buildCategoriesGrid(context, categories, l10n),
              loading: () => const CircularProgressIndicator(),
              error: (error, stackTrace) => Text(l10n.error),
            ),
          ],
        ),
      ),
    );
  }

  Widget _buildTypeToggle(AppLocalizations l10n) {
    return Container(
      decoration: BoxDecoration(
        color: Colors.white,
        borderRadius: BorderRadius.circular(30),
        border: Border.all(color: AppColors.border),
      ),
      child: Row(
        children: [
          // Expense Button
          Expanded(
            child: GestureDetector(
              onTap: () {
                setState(() {
                  _type = 'expense';
                  // Reset category selection when type changes
                  _selectedCategoryId = null;
                  _selectedCategoryName = null;
                  _selectedCategoryIcon = null;
                });
              },
              child: Container(
                padding: const EdgeInsetsDirectional.symmetric(vertical: 12),
                decoration: BoxDecoration(
                  color: _type == 'expense'
                      ? AppColors.primary
                      : Colors.transparent,
                  borderRadius: BorderRadius.circular(30),
                ),
                child: Row(
                  mainAxisAlignment: MainAxisAlignment.center,
                  children: [
                    Icon(
                      Icons.arrow_downward,
                      color: _type == 'expense' ? Colors.white : Colors.grey,
                      size: 18,
                    ),
                    const SizedBox(width: 8),
                    Text(
                      l10n.expenseType,
                      style: TextStyle(
                        color: _type == 'expense' ? Colors.white : Colors.grey,
                        fontWeight: FontWeight.bold,
                      ),
                    ),
                  ],
                ),
              ),
            ),
          ),
          // Income Button
          Expanded(
            child: GestureDetector(
              onTap: () {
                setState(() {
                  _type = 'income';
                  // Reset category selection when type changes
                  _selectedCategoryId = null;
                  _selectedCategoryName = null;
                  _selectedCategoryIcon = null;
                });
              },
              child: Container(
                padding: const EdgeInsetsDirectional.symmetric(vertical: 12),
                decoration: BoxDecoration(
                  color: _type == 'income'
                      ? AppColors.income.withAlpha(26)
                      : Colors.transparent,
                  borderRadius: BorderRadius.circular(30),
                ),
                child: Row(
                  mainAxisAlignment: MainAxisAlignment.center,
                  children: [
                    Icon(
                      Icons.arrow_upward,
                      color: _type == 'income' ? AppColors.income : Colors.grey,
                      size: 18,
                    ),
                    const SizedBox(width: 8),
                    Text(
                      l10n.incomeType,
                      style: TextStyle(
                        color: _type == 'income'
                            ? AppColors.income
                            : Colors.grey,
                        fontWeight: FontWeight.bold,
                      ),
                    ),
                  ],
                ),
              ),
            ),
          ),
        ],
      ),
    );
  }

  Widget _buildAmountInput(ThemeData theme) {
    return Column(
      children: [
        Text(
          '₪',
          style: theme.textTheme.headlineMedium?.copyWith(color: Colors.grey),
        ),
        TextField(
          controller: _amountController,
          keyboardType: const TextInputType.numberWithOptions(decimal: true),
          textAlign: TextAlign.center,
          style: theme.textTheme.headlineLarge?.copyWith(fontSize: 48),
          decoration: const InputDecoration(
            border: InputBorder.none,
            focusedBorder: InputBorder.none,
            enabledBorder: InputBorder.none,
            hintText: '0.00',
          ),
        ),
      ],
    );
  }

  Widget _buildCategoriesGrid(
    BuildContext context,
    List categories,
    AppLocalizations l10n,
  ) {
    // Filter categories by selected type
    final filteredCategories = categories
        .where((c) => c.type == _type)
        .toList();

    if (filteredCategories.isEmpty) {
      return Padding(
        padding: const EdgeInsetsDirectional.all(16),
        child: Text(
          l10n.noCategoriesFound,
          style: Theme.of(context).textTheme.bodyMedium,
        ),
      );
    }

    return Wrap(
      spacing: 12,
      runSpacing: 12,
      children: filteredCategories.map((cat) {
        final isSelected = _selectedCategoryId == cat.id;
        final displayName = TranslationHelper.getCategoryName(
          context,
          cat.name,
        );

        return GestureDetector(
          onTap: () => setState(() {
            _selectedCategoryId = cat.id;
            _selectedCategoryName = cat.name;
            _selectedCategoryIcon = cat.icon;
          }),
          child: Container(
            padding: const EdgeInsetsDirectional.symmetric(
              horizontal: 16,
              vertical: 12,
            ),
            decoration: BoxDecoration(
              color: isSelected ? AppColors.primary : Colors.white,
              borderRadius: BorderRadius.circular(AppRadius.chip),
              border: Border.all(
                color: isSelected ? AppColors.primary : AppColors.border,
              ),
            ),
            child: Row(
              mainAxisSize: MainAxisSize.min,
              children: [
                Icon(
                  IconHelper.getIcon(cat.icon),
                  size: 18,
                  color: isSelected ? Colors.white : AppColors.textPrimary,
                ),
                const SizedBox(width: 8),
                Text(
                  displayName,
                  style: TextStyle(
                    color: isSelected ? Colors.white : AppColors.textPrimary,
                  ),
                ),
              ],
            ),
          ),
        );
      }).toList(),
    );
  }
}
